


#src\main\resources\application-dev.yml
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: video-api
  servlet:
    multipart:
      max-file-size: 10MB

  documentation:
    swagger-ui:
      # 生产环境需要关闭
      enabled: true

File:
  uploadPath: D:\web\ideaProjects\java_video\img
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml


server:
  port: 9090
  servlet:
    context-path: /api