
server.port:
server.servlet.context-path: /api

#src\main\resources\application-dev.yml
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: video-api
springfox:
  documentation:
    swagger-ui:
      # 生产环境需要关闭
      enabled: true

File:
  uploadPath: D:\web\ideaProjects\java_video\img
mybatis:
  configuration:
    map-underscore-to-camel-case: true



  profiles:
    active=@env@: